function TABLE = readCineECGLog2Table(fn)
% [~,TXT,~] = xlsread('C:\Users\peter\Peacs\Development\code\CineECG\logAlvaleheader.xlsx');TXT=TXT(1,2:end)'

HEADAV = headerAV();
HEADAV2 = headerAV2();
HEADAV3 = headerAV3();

HEADV = headerV();
HEADV5635 = header5636();
HEADV5666 = header5666();
HEADV6284 = header6284();
HEADV6384 = header6384();
HEADV6399 = header6399();
HEADV6478 = header6478();
HEADV6543 = header6543();
HEADV6920 = header6920();
HEADV7024 = header7024();
% make sure C:/tmp exists!!!
if exist(fn,'file')
    %     status = copyfile(fn, 'c:/tmp/tmp.csv');
    %     TABLE  = readtable('c:/tmp/tmp.csv','Delimiter',',');
    %     delete('c:/tmp/tmp.csv')
    TABLE  = readtable(fn,'Delimiter',',');
    if size(TABLE,2) == size(HEADV7024,2)
        TABLE.Properties.VariableNames = HEADV7024;
    elseif size(TABLE,2) == size(HEADV6920,2)
        TABLE.Properties.VariableNames = HEADV6920;
    elseif size(TABLE,2) == size(HEADV6543,2)
        TABLE.Properties.VariableNames = HEADV6543;
    elseif size(TABLE,2) == size(HEADV6478,2)
        TABLE.Properties.VariableNames = HEADV6478;
    elseif size(TABLE,2) == size(HEADV6284,2)
        TABLE.Properties.VariableNames = HEADV6284;
    elseif size(TABLE,2) == size(HEADV6384,2)
        TABLE.Properties.VariableNames = HEADV6384;
    elseif size(TABLE,2) == size(HEADV6399,2)
        TABLE.Properties.VariableNames = HEADV6399;
    elseif size(TABLE,2) == size(HEADAV,2)
        TABLE.Properties.VariableNames = HEADAV';
        remove = 1:length(HEADAV);
        use = [2 4:length(HEADAV)];
        remove(use)=[];
        TABLE = removevars(TABLE, HEADAV(remove));
    elseif size(TABLE,2) == size(HEADAV2,2)
        TABLE.Properties.VariableNames = HEADAV2';
        remove = 1:length(HEADAV2);
        use = [2 4:length(HEADAV2)];
        remove(use)=[];
        TABLE = removevars(TABLE, HEADAV2(remove));
    elseif size(TABLE,2) == size(HEADAV3,2)
        TABLE.Properties.VariableNames = HEADAV3';
    elseif size(TABLE,2) == size(HEADV,2)
        if size(TABLE,2) > size(HEADV,2)
            TABLE(:,size(HEADV,2)+1:end) =[];
        end
        TABLE.Properties.VariableNames = HEADV';
        remove = 1:length(HEADV);
        use = [2 4:length(HEADV)];
        remove(use)=[];
        TABLE = removevars(TABLE, HEADV(remove));
    elseif size(TABLE,2) == size(HEADV5635,2)
        TABLE.Properties.VariableNames = HEADV5635';
    elseif size(TABLE,2) == size(HEADV5666,2)
        TABLE.Properties.VariableNames = HEADV5666';
    else
        error('no matching header definition')
    end

else
    error(['file: ' fn ' does not exist']);
end
%%
function HEADV7024 = header7024()
TABLE  = readtable('CineEcgLogHeader7024.xlsx');
HEADV7024 = TABLE.Properties.VariableNames(2:end);

%%
function HEADV6920 = header6920()
TABLE  = readtable('CineEcgLogHeader6920.xlsx');
HEADV6920 = TABLE.Properties.VariableNames(2:end);

%%
function HEAD6543 = header6543()
TABLE  = readtable('CineEcgLogHeader6543.xlsx');
HEAD6543 = TABLE.Properties.VariableNames(2:end);

%%
function HEAD6478 = header6478()
TABLE  = readtable('CineEcgLogHeader6478.xlsx');
HEAD6478 = TABLE.Properties.VariableNames(2:end);
%%
%%
function HEAD9384 = header6384()
TABLE  = readtable('CineEcgLogHeader6394.xlsx');
HEAD9384 = TABLE.Properties.VariableNames(2:end);
%%
function HEAD6284 = header6284()
TABLE  = readtable('CineEcgLogHeader6284.xlsx');
HEAD6284 = TABLE.Properties.VariableNames(2:end);
%%
function HEAD6399 = header6399()
TABLE  = readtable('CineEcgLogHeader6399.xlsx');
HEAD6399 = TABLE.Properties.VariableNames(2:end);

%%
function HV = header5666()
HV=[...
    {'date'                                                                       }...
    {'patient ID'                                                                 }...
    {'ECG case'                                                                   }...
    {'ECG file'                                                                   }...
    {'ECG ID'                                                                     }...
    {'RRint'                                                                      }...
    {'type'}...
    {'QRS duration '                                                             }...
    {'Ohmega point'                                                               }...
    {'QT'                                                                         }...
    {'mean ST amplitude 10-60ms'                                                  }...
    {'Peak T wave'                                                                }...
    {'relative ST  '                                                              }...
    {'mode'                                                                       }...
    {'RV focus'                                                                  }...
    {'LV focus'                                                                   }...
    {'initial angle'                                                              }...
    {'LV latest'                                                                  }...
    {'RV latest'                                                                  }...
    {'mean TSI distance'                                                          }...
    {'distance focus to latest'                                                   }...
    {'qrs area'                                                                   }...
    {'3D qrs area'                                                                }...
    {'KORS qrs area'                                                              }...
    {'KORS 3D qrs area'                                                           }...
    {'TCR QRS'                                                                    }...
    {'minimum TCR QRS'                                                            }...
    {'TCR STT'                                                                    }...
    {'TCR Beat'                                                                   }...
    {'template nr'                                                                }...
    {'initial Vector in myocard'                                                  }...
    {'temp1'                                                                      }...
    {'temp2'                                                                      }...
    {'QRS mTSI Location Septum'                                                  }...
    {'QRS mTSI Location LV'                                                      }...
    {'QRS mTSI Location RV'                                                       }...
    {'STT mTSI Location Septum'                                                   }...
    {'STT mTSI Location LV'                                                      }...
    {'STT mTSI Localization RV'                                                  }...
    {'Terminal QRS mTSI Location Septum'                                          }...
    {'Terminal QRS mTSI Location LV'                                              }...
    {'Terminal QRS mTSI Location RV'                                              }...
    {'Terminal QRS-ST 110-150 mTSI Location Septum'                               }...
    {'Terminal QRS-ST 110-150 mTSI Location LV'                                }...
    {'Terminal QRS-ST 110-150 mTSI Location RV'                                 }...
    {'STpeak mTSI Location Septum'                                                }...
    {'STpeak mTSI Location LV'                                                    }...
    {'STpeak mTSI Location RV'                                                    }...
    {'Tpeak-Tend mTSI Location Septum'                                            }...
    {'Tpeak-Tend mTSI Location LV'                                                }...
    {'Tpeak-Tend mTSI Location RV'                                                }...
    {'Initial QRS mTSI Direction X'                                               }...
    {'Initial QRS mTSI Direction Y'                                               }...
    {'Initial QRS mTSI Direction Z'                                               }...
    {'Terminal QRS mTSI Direction X'                                              }...
    {'Terminal QRS mTSI Direction Y'                                              }...
    {'Terminal QRS mTSI Direction Z'                                              }...
    {'Terminal QRS-ST 110-150 mTSI Direction X'                                  }...
    {'Terminal QRS-ST 110-150 mTSI Direction Y'                                  }...
    {'Terminal QRS-ST 110-150 mTSI Direction Z'                                  }...
    {'STpeak mTSI Direction X'                                                    }...
    {'STpeak mTSI Direction Y'                                                    }...
    {'STpeak mTSI Direction Z'                                                    }...
    {'Tpeak-Tend mTSI Direction X'                                                }...
    {'Tpeak-Tend mTSI Direction Y'                                                }...
    {'Tpeak-Tend mTSI Direction Z'                                                }...
    {'QRS mTSI Direction X'                                                       }...
    {'QRS mTSI Direction Y'                                                       }...
    {'QRS mTSI Direction Z'                                                       }...
    {'STT mTSI Direction X'                                                       }...
    {'STT mTSI Direction Y'                                                       }...
    {'STT mTSI Direction Z'                                                       }...
    {'VCG QRS axis X'                                                             }...
    {'VCG QRS axis Y'                                                             }...
    {'VCG QRS axis Z'                                                             }...
    {'VCG QRS axis length'                                                        }...
    {'VCG Twave axis X'                                                           }...
    {'VCG Twave axis Y'                                                           }...
    {'VCG Twave axis Z'                                                           }...
    {'VCG Twave axis length'                                                      }...
    {'temp3'                                                                      }...
    {'temp4'                                                                      }...
    {'Pwave first Inflection point'                                               }...
    {'VCG Pwave axis X'                                                           }...
    {'VCG Pwave  axis Y'                                                          }...
    {'VCG Pwave  axis Z'                                                          }...
    {'Pwave Location X'                                                           }...
    {'Pwave Location Y'                                                           }...
    {'Pwave Location Z'                                                           }...
    {'Initial Pwave Location  X'                                                  }...
    {'Initial Pwave Location Y'                                                   }...
    {'Initial Pwave Location Z'                                                   }...
    {'TerminalPwave Location X'                                                   }...
    {'Terminal Pwave Location Y'                                                  }...
    {'Terminal Pwave Location Z'                                                  }...
    {'Pwave DirectionX'                                                           }...
    {'Pwave Direction Y'                                                          }...
    {'Pwave Direction  Z'                                                         }...
    {'Initial Pwave Direction X'                                                 }...
    {'Initial Pwave Direction Y'                                                 }...
    {'Initial Pwave Direction Z'                                                 }...
    {'TerminalPwave Direction X'                                                 }...
    {'Terminal Pwave Direction Y'                                                }...
    {'Terminal Pwave Direction Z'                                                }...
    {'CineECG activation in normal range'                                        }...
    {'CineECG earlyST in normal range'                                           }...
    {'CineECG STT in normal range'                                                }...
    {'CineECG 0-110 in normal range'                                             }...
    {'CineECG 110-200 in normal range'                                           }...
    {'CineECG 200 tpeak in normal range'                                         }...
    {'CineECG tptend in normal range'                                            }...
    {'ECG activation in normal range'                                            }...
    {'ECG earlyST in normal range'                                               }...
    {'ECG STT in normal range'                                                    }...
    {'ECG 0-110 in normal range'                                                 }...
    {'ECG 110-200 in normal range'                                               }...
    {'ECG 200 tpeak in normal range'                                             }...
    {'ECG tptend in normal range'                                                }...
    {'HP classification'                                                          }...
    {'discordant QRS Twave'                                                       }...
    {'CineECG iso QRST angle'                                                     }...
    {'STT segment'                                                                }...
    {'LvSTT segment'                                                              }...
    {'ischemia Estimate'                                                          }...
    {'median  Twave Slope Dominant TMP'                                           }...
    {'median  Twave SlopeRms'                                                     }];

%%
function HV = header5636()
HV=[...
    {'date'                                                                       }...
    {'patient ID'                                                                 }...
    {'ECG case'                                                                   }...
    {'ECG file'                                                                   }...
    {'RRint'                                                                      }...
    {'type'}...
    {'QRS  duration '                                                             }...
    {'Ohmega point'                                                               }...
    {'QT'                                                                         }...
    {'mean ST amplitude 10-60ms'                                                  }...
    {'Peak T wave'                                                                }...
    {'relative ST  '                                                              }...
    {'mode'                                                                       }...
    {'RV  focus'                                                                  }...
    {'LV focus'                                                                   }...
    {'initial angle'                                                              }...
    {'LV latest'                                                                  }...
    {'RV latest'                                                                  }...
    {'mean TSI distance'                                                          }...
    {'distance focus to latest'                                                   }...
    {'qrs area'                                                                   }...
    {'3D qrs area'                                                                }...
    {'KORS qrs area'                                                              }...
    {'KORS 3D qrs area'                                                           }...
    {'TCR QRS'                                                                    }...
    {'minimum TCR QRS'                                                            }...
    {'TCR STT'                                                                    }...
    {'TCR Beat'                                                                   }...
    {'template nr'                                                                }...
    {'initial Vector in myocard'                                                  }...
    {'temp1'                                                                      }...
    {'temp2'                                                                      }...
    {'QRS mTSI Location  Septum'                                                  }...
    {'QRS mTSI Location  LV'                                                      }...
    {'QRS mTSI Location RV'                                                       }...
    {'STT mTSI Location Septum'                                                   }...
    {'STT mTSI Location  LV'                                                      }...
    {'STT mTSI Localization  RV'                                                  }...
    {'Terminal QRS mTSI Location Septum'                                          }...
    {'Terminal QRS mTSI Location LV'                                              }...
    {'Terminal QRS mTSI Location RV'                                              }...
    {'Terminal QRS-ST mTSI 110-150 Location Septum'                               }...
    {'Terminal QRS -ST 110-150 mTSI  Location  LV'                                }...
    {'Terminal QRS-ST 110-150 mTSI  Location  RV'                                 }...
    {'STpeak mTSI Location Septum'                                                }...
    {'STpeak mTSI Location LV'                                                    }...
    {'STpeak mTSI Location RV'                                                    }...
    {'Tpeak-Tend mTSI Location Septum'                                            }...
    {'Tpeak-Tend mTSI Location LV'                                                }...
    {'Tpeak-Tend mTSI Location RV'                                                }...
    {'Initial QRS mTSI Direction X'                                               }...
    {'Initial QRS mTSI Direction Y'                                               }...
    {'Initial QRS mTSI Direction Z'                                               }...
    {'Terminal QRS mTSI Direction X'                                              }...
    {'Terminal QRS mTSI Direction Y'                                              }...
    {'Terminal QRS mTSI Direction Z'                                              }...
    {'Terminal QRS-ST 110-150 mTSI  Direction X'                                  }...
    {'Terminal QRS-ST 110-150 mTSI  Direction Y'                                  }...
    {'Terminal QRS-ST 110-150 mTSI  Direction Z'                                  }...
    {'STpeak mTSI Direction X'                                                    }...
    {'STpeak mTSI Direction Y'                                                    }...
    {'STpeak mTSI Direction Z'                                                    }...
    {'Tpeak-Tend mTSI Direction X'                                                }...
    {'Tpeak-Tend mTSI Direction Y'                                                }...
    {'Tpeak-Tend mTSI Direction Z'                                                }...
    {'QRS mTSI Direction X'                                                       }...
    {'QRS mTSI Direction Y'                                                       }...
    {'QRS mTSI Direction Z'                                                       }...
    {'STT mTSI Direction X'                                                       }...
    {'STT mTSI Direction Y'                                                       }...
    {'STT mTSI Direction Z'                                                       }...
    {'VCG QRS axis X'                                                             }...
    {'VCG QRS axis Y'                                                             }...
    {'VCG QRS axis Z'                                                             }...
    {'VCG QRS axis length'                                                        }...
    {'VCG Twave axis X'                                                           }...
    {'VCG Twave axis Y'                                                           }...
    {'VCG Twave axis Z'                                                           }...
    {'VCG Twave axis length'                                                      }...
    {'temp3'                                                                      }...
    {'temp4'                                                                      }...
    {'Pwave first Inflection point'                                               }...
    {'VCG Pwave axis X'                                                           }...
    {'VCG Pwave  axis Y'                                                          }...
    {'VCG Pwave  axis Z'                                                          }...
    {'Pwave Location X'                                                           }...
    {'Pwave Location Y'                                                           }...
    {'Pwave Location Z'                                                           }...
    {'Initial Pwave Location  X'                                                  }...
    {'Initial Pwave Location Y'                                                   }...
    {'Initial Pwave Location Z'                                                   }...
    {'TerminalPwave Location X'                                                   }...
    {'Terminal Pwave Location Y'                                                  }...
    {'Terminal Pwave Location Z'                                                  }...
    {'Pwave DirectionX'                                                           }...
    {'Pwave Direction Y'                                                          }...
    {'Pwave Direction  Z'                                                         }...
    {'Initial Pwave Direction  X'                                                 }...
    {'Initial Pwave Direction  Y'                                                 }...
    {'Initial Pwave Direction  Z'                                                 }...
    {'TerminalPwave Direction  X'                                                 }...
    {'Terminal Pwave Direction  Y'                                                }...
    {'Terminal Pwave Direction  Z'                                                }...
    {'CineECG  activation in normal range'                                        }...
    {'CineECG  earlyST in normal range'                                           }...
    {'CineECG STT in normal range'                                                }...
    {'CineECG  0-110 in normal range'                                             }...
    {'CineECG  110-200 in normal range'                                           }...
    {'CineECG  200 tpeak in normal range'                                         }...
    {'CineECG  tptend in normal range'                                            }...
    {'ECG  activation in normal range'                                            }...
    {'ECG  earlyST in normal range'                                               }...
    {'ECG STT in normal range'                                                    }...
    {'ECG  0-110 in normal range'                                                 }...
    {'ECG  110-200 in normal range'                                               }...
    {'ECG  200 tpeak in normal range'                                             }...
    {'ECG  tptend in normal range'                                                }...
    {'HP classification'                                                          }...
    {'discordant QRS Twave'                                                       }...
    {'CineECG iso QRST angle'                                                     }...
    {'STT segment'                                                                }...
    {'LvSTT segment'                                                              }...
    {'ischemia Estimate'                                                          }...
    {'median  Twave Slope Dominant TMP'                                           }...
    {'median  Twave SlopeRms'                                                     }];

%%
function HEADV = headerV()
HEADV =[{'date'  };...
    {'patient ID'};...
    {'ECG case' };...
    {'ECG file' };...
    {'RRint'};...
    {'type'};...
    {'QRS  duration '};...
    {'Ohmega point'};...
    {'QT'};...
    {'QTc bazett'};...
    {'Peak T wave' };...
    {'relative ST  '};...
    {'mode'};...
    {'RV  focus'};...
    {'LV focus' };...
    {'initial angle'};...
    {'LV latest'};...
    {'RV latest'};...
    {'mean TSI distance'};...
    {'distance focus to latest'};...
    {'qrs area' };...
    {'3D qrs area' };...
    {'KORS qrs area'};...
    {'KORS 3D qrs area' };...
    {'TCR QRS'  };...
    {'minimum TCR QRS'  };...
    {'TCR STT'  };...
    {'TCR Beat' };...
    {'template nr' };...
    {'initial Vector in myocard' };...
    {'temp1'};...
    {'temp2'};...
    {'QRS mTSI Location  Septum' };...
    {'QRS mTSI Location  LV'   };...
    {'QRS mTSI Location RV'};...
    {'STT mTSI Location Septum'};...
    {'STT mTSI Location  LV'   };...
    {'STT mTSI Localization  RV' };...
    {'Terminal QRS mTSI Location Septum' };...
    {'Terminal QRS mTSI Location LV'  };...
    {'Terminal QRS mTSI Location RV'  };...
    {'Terminal QRS-ST mTSI 110-150 Location Septum'  };...
    {'Terminal QRS -ST 110-150 mTSI  Location  LV'   };...
    {'Terminal QRS-ST 110-150 mTSI  Location  RV'};...
    {'STpeak mTSI Location Septum'};...
    {'STpeak mTSI Location LV' };...
    {'STpeak mTSI Location RV' };...
    {'Tpeak-Tend mTSI Location Septum'};...
    {'Tpeak-Tend mTSI Location LV'};...
    {'Tpeak-Tend mTSI Location RV'};...
    {'Initial QRS mTSI Direction X'   };...
    {'Initial QRS mTSI Direction Y'   };...
    {'Initial QRS mTSI Direction Z'   };...
    {'Terminal QRS mTSI Direction X'  };...
    {'Terminal QRS mTSI Direction Y'  };...
    {'Terminal QRS mTSI Direction Z'  };...
    {'Terminal QRS-ST 110-150 mTSI  Direction X'};...
    {'Terminal QRS-ST 110-150 mTSI  Direction Y'};...
    {'Terminal QRS-ST 110-150 mTSI  Direction Z'};...
    {'STpeak mTSI Direction X' };...
    {'STpeak mTSI Direction Y' };...
    {'STpeak mTSI Direction Z' };...
    {'Tpeak-Tend mTSI Direction X'};...
    {'Tpeak-Tend mTSI Direction Y'};...
    {'Tpeak-Tend mTSI Direction Z'};...
    {'QRS mTSI Direction X'};...
    {'QRS mTSI Direction Y'};...
    {'QRS mTSI Direction Z'};...
    {'STT mTSI Direction X'};...
    {'STT mTSI Direction Y'};...
    {'STT mTSI Direction Z'};...
    {'VCG QRS axis X'   };...
    {'VCG QRS axis Y'   };...
    {'VCG QRS axis Z'   };...
    {'VCG QRS axis length'};...
    {'VCG Twave axis X' };...
    {'VCG Twave axis Y' };...
    {'VCG Twave axis Z' };...
    {'VCG Twave axis length'};...
    {'temp3'};...
    {'QRS in normal range'};...
    {'STT in normal range'};...
    {'initial QRS in normal range'   };...
    {'terminal QRS in normal range'};...
    {'QRS-S150 in normal range'  };...
    {'STpeak in normal range'  };...
    {'TpTe in normal range'};...
    {'used normal limit'};...
    {'median  Twave Slope Dominant TMP'};...
    {'median  Twave SlopeRms'  };...
    ]';

%%
function HEADAV = headerAV()

HEADAV =[{'date'  };...
    {'patient ID'};...
    {'ECG case' };...
    {'ECG file' };...
    {'RRint'};...
    {'type'};...
    {'QRS  duration '};...
    {'Ohmega point'};...
    {'QT'};...
    {'QTc bazett'};...
    {'Peak T wave' };...
    {'relative ST  '};...
    {'mode'};...
    {'RV  focus'};...
    {'LV focus' };...
    {'initial angle'};...
    {'LV latest'};...
    {'RV latest'};...
    {'mean TSI distance'};...
    {'distance focus to latest'};...
    {'qrs area' };...
    {'3D qrs area' };...
    {'KORS qrs area'};...
    {'KORS 3D qrs area' };...
    {'TCR QRS'  };...
    {'minimum TCR QRS'  };...
    {'TCR STT'  };...
    {'TCR Beat' };...
    {'template nr' };...
    {'initial Vector in myocard' };...
    {'temp1'};...
    {'temp2'};...
    {'QRS mTSI Location  Septum' };...
    {'QRS mTSI Location  LV'   };...
    {'QRS mTSI Location RV'};...
    {'STT mTSI Location Septum'};...
    {'STT mTSI Location  LV'   };...
    {'STT mTSI Localization  RV' };...
    {'Terminal QRS mTSI Location Septum' };...
    {'Terminal QRS mTSI Location LV'  };...
    {'Terminal QRS mTSI Location RV'  };...
    {'Terminal QRS-ST mTSI 110-150 Location Septum'  };...
    {'Terminal QRS -ST 110-150 mTSI  Location  LV'   };...
    {'Terminal QRS-ST 110-150 mTSI  Location  RV'};...
    {'STpeak mTSI Location Septum'};...
    {'STpeak mTSI Location LV' };...
    {'STpeak mTSI Location RV' };...
    {'Tpeak-Tend mTSI Location Septum'};...
    {'Tpeak-Tend mTSI Location LV'};...
    {'Tpeak-Tend mTSI Location RV'};...
    {'Initial QRS mTSI Direction X'   };...
    {'Initial QRS mTSI Direction Y'   };...
    {'Initial QRS mTSI Direction Z'   };...
    {'Terminal QRS mTSI Direction X'  };...
    {'Terminal QRS mTSI Direction Y'  };...
    {'Terminal QRS mTSI Direction Z'  };...
    {'Terminal QRS-ST 110-150 mTSI  Direction X'};...
    {'Terminal QRS-ST 110-150 mTSI  Direction Y'};...
    {'Terminal QRS-ST 110-150 mTSI  Direction Z'};...
    {'STpeak mTSI Direction X' };...
    {'STpeak mTSI Direction Y' };...
    {'STpeak mTSI Direction Z' };...
    {'Tpeak-Tend mTSI Direction X'};...
    {'Tpeak-Tend mTSI Direction Y'};...
    {'Tpeak-Tend mTSI Direction Z'};...
    {'QRS mTSI Direction X'};...
    {'QRS mTSI Direction Y'};...
    {'QRS mTSI Direction Z'};...
    {'STT mTSI Direction X'};...
    {'STT mTSI Direction Y'};...
    {'STT mTSI Direction Z'};...
    {'VCG QRS axis X'   };...
    {'VCG QRS axis Y'   };...
    {'VCG QRS axis Z'   };...
    {'VCG QRS axis length'};...
    {'VCG Twave axis X' };...
    {'VCG Twave axis Y' };...
    {'VCG Twave axis Z' };...
    {'VCG Twave axis length'};...
    {'temp3'};...
    {'temp4'};...
    {'Pwave inflection point'};...
    {'VCG Pwave axis X'};...
    {'VCG Pwave  axis Y'};...
    {'VCG Pwave  axis Z'};...
    {'Pwave Location X'};...
    {'Pwave Location Y'};...
    {'Pwave Location Z'};...
    {'Initial Pwave Location X'};...
    {'Initial Pwave Location Y'};...
    {'Initial Pwave Location Z'};...
    {'TerminalPwave Location X'};...
    {'Terminal Pwave Location Y'};...
    {'Terminal Pwave Location Z'};...
    {'Pwave Direction X'};...
    {'Pwave Direction Y'};...
    {'Pwave Direction Z'};...
    {'Initial Pwave Direction X'};...
    {'Initial Pwave Direction Y'};...
    {'Initial Pwave Direction Z'};...
    {'Terminal Pwave Direction X'};...
    {'Terminal Pwave Direction Y'};...
    {'Terminal Pwave Direction Z'};...
    {'QRS in normal range'};...
    {'STT in normal range'};...
    {'initial QRS in normal range'   };...
    {'terminal QRS in normal range'};...
    {'QRS-S150 in normal range'  };...
    {'STpeak in normal range'  };...
    {'TpTe in normal range'};...
    {'used normal limit'};...
    {'Dont know'};...
    {'median  Twave Slope Dominant TMP'};...
    {'median  Twave SlopeRms'  };...
    ]';

%%
function HEADAV2=headerAV2()
HEADAV2 =[{'date'  };...
    {'patient ID'};...
    {'ECG case' };...
    {'ECG file' };...
    {'RRint'};...
    {'type'};...
    {'QRS  duration '};...
    {'Ohmega point'};...
    {'QT'};...
    {'mean ST amplitude 10-60ms'};...
    {'Peak T wave' };...
    {'relative ST  '};...
    {'mode'};...
    {'RV  focus'};...
    {'LV focus' };...
    {'initial angle'};...
    {'LV latest'};...
    {'RV latest'};...
    {'mean TSI distance'};...
    {'distance focus to latest'};...
    {'qrs area' };...
    {'3D qrs area' };...
    {'KORS qrs area'};...
    {'KORS 3D qrs area' };...
    {'TCR QRS'  };...
    {'minimum TCR QRS'  };...
    {'TCR STT'  };...
    {'TCR Beat' };...
    {'template nr' };...
    {'initial Vector in myocard' };...
    {'temp1'};...
    {'temp2'};...
    {'QRS mTSI Location  Septum' };...
    {'QRS mTSI Location  LV'   };...
    {'QRS mTSI Location RV'};...
    {'STT mTSI Location Septum'};...
    {'STT mTSI Location  LV'   };...
    {'STT mTSI Localization  RV' };...
    {'Terminal QRS mTSI Location Septum' };...
    {'Terminal QRS mTSI Location LV'  };...
    {'Terminal QRS mTSI Location RV'  };...
    {'Terminal QRS-ST mTSI 110-150 Location Septum'  };...
    {'Terminal QRS -ST 110-150 mTSI  Location  LV'   };...
    {'Terminal QRS-ST 110-150 mTSI  Location  RV'};...
    {'STpeak mTSI Location Septum'};...
    {'STpeak mTSI Location LV' };...
    {'STpeak mTSI Location RV' };...
    {'Tpeak-Tend mTSI Location Septum'};...
    {'Tpeak-Tend mTSI Location LV'};...
    {'Tpeak-Tend mTSI Location RV'};...
    {'Initial QRS mTSI Direction X'   };...
    {'Initial QRS mTSI Direction Y'   };...
    {'Initial QRS mTSI Direction Z'   };...
    {'Terminal QRS mTSI Direction X'  };...
    {'Terminal QRS mTSI Direction Y'  };...
    {'Terminal QRS mTSI Direction Z'  };...
    {'Terminal QRS-ST 110-150 mTSI  Direction X'};...
    {'Terminal QRS-ST 110-150 mTSI  Direction Y'};...
    {'Terminal QRS-ST 110-150 mTSI  Direction Z'};...
    {'STpeak mTSI Direction X' };...
    {'STpeak mTSI Direction Y' };...
    {'STpeak mTSI Direction Z' };...
    {'Tpeak-Tend mTSI Direction X'};...
    {'Tpeak-Tend mTSI Direction Y'};...
    {'Tpeak-Tend mTSI Direction Z'};...
    {'QRS mTSI Direction X'};...
    {'QRS mTSI Direction Y'};...
    {'QRS mTSI Direction Z'};...
    {'STT mTSI Direction X'};...
    {'STT mTSI Direction Y'};...
    {'STT mTSI Direction Z'};...
    {'VCG QRS axis X'   };...
    {'VCG QRS axis Y'   };...
    {'VCG QRS axis Z'   };...
    {'VCG QRS axis length'};...
    {'VCG Twave axis X' };...
    {'VCG Twave axis Y' };...
    {'VCG Twave axis Z' };...
    {'VCG Twave axis length'};...
    {'temp3'};...
    {'temp4'};...
    {'Pwave inflection point'};...
    {'VCG Pwave axis X'};...
    {'VCG Pwave  axis Y'};...
    {'VCG Pwave  axis Z'};...
    {'Pwave Location X'};...
    {'Pwave Location Y'};...
    {'Pwave Location Z'};...
    {'Initial Pwave Location X'};...
    {'Initial Pwave Location Y'};...
    {'Initial Pwave Location Z'};...
    {'TerminalPwave Location X'};...
    {'Terminal Pwave Location Y'};...
    {'Terminal Pwave Location Z'};...
    {'Pwave Direction X'};...
    {'Pwave Direction Y'};...
    {'Pwave Direction Z'};...
    {'Initial Pwave Direction X'};...
    {'Initial Pwave Direction Y'};...
    {'Initial Pwave Direction Z'};...
    {'Terminal Pwave Direction X'};...
    {'Terminal Pwave Direction Y'};...
    {'Terminal Pwave Direction Z'};...
    {'QRS in normal range'};...
    {'STT in normal range'};...
    {'likelihood IRBBB'   };...
    {'likelihood RBBB'};...
    {'likelihood ILBBB'  };...
    {'likelihood LBBB'  };...
    {'not used'};...
    {'used normal limit'};...
    {'STT segment'};...
    {'LvSTT segment'};...
    {'Ischemia Estimate'};...
    {'median  Twave Slope Dominant TMP'};...
    {'median  Twave SlopeRms'  };...
    ]';


function HEADAV3=headerAV3()
HEADAV3 =[...
    {'date'                                                 };...
    {'patient ID'                                           };...
    {'ECG case'                                             };...
    {'ECG file'                                             };...
    {'ECGid'                                                };...
    {'RRint'                                                };...
    {'type'};...
    {'QRS duration '                                        };...
    {'Ohmega point'                                         };...
    {'QT'                                                   };...
    {'mean ST amplitude 10-60ms'                            };...
    {'Peak T wave'                                          };...
    {'relative ST '                                         };...
    {'mode'                                                 };...
    {'RV focus'                                             };...
    {'LV focus'                                             };...
    {'initial angle'                                        };...
    {'LV latest'                                            };...
    {'RV latest'                                            };...
    {'mean TSI distance'                                    };...
    {'distance focus to latest'                             };...
    {'qrs area'                                             };...
    {'3D qrs area'                                          };...
    {'KORS qrs area'                                        };...
    {'KORS 3D qrs area'                                     };...
    {'TCR QRS'                                              };...
    {'minimum TCR QRS'                                      };...
    {'TCR STT'                                              };...
    {'TCR Beat'                                             };...
    {'template nr'                                          };...
    {'initial Vector in myocard'                            };...
    {'TCR 0-89'                                             };...
    {'temp2'                                                };...
    {'QRS mTSI Location Septum'                             };...
    {'QRS mTSI Location LV'                                 };...
    {'QRS mTSI Location RV'                                 };...
    {'STT mTSI Location Septum'                             };...
    {'STT mTSI Location LV'                                 };...
    {'STT mTSI Localization RV'                             };...
    {'Initial QRS mTSI Location Septum'                     };...
    {'Initial  QRS mTSI Location LV'                        };...
    {'Initial  QRS mTSI Location RV'                        };...
    {'Terminal QRS mTSI Location Septum'                    };...
    {'Terminal QRS mTSI Location LV'                        };...
    {'Terminal QRS mTSI Location RV'                        };...
    {'Terminal QRS-ST mTSI 110-150 Location Septum'         };...
    {'Terminal QRS -ST 110-150 mTSI Location LV'            };...
    {'Terminal QRS-ST 110-150 mTSI Location RV'             };...
    {'STpeak mTSI Location Septum'                          };...
    {'STpeak mTSI Location LV'                              };...
    {'STpeak mTSI Location RV'                              };...
    {'Tpeak-Tend mTSI Location Septum'                      };...
    {'Tpeak-Tend mTSI Location LV'                          };...
    {'Tpeak-Tend mTSI Location RV'                          };...
    {'Initial QRS mTSI Direction X'                         };...
    {'Initial QRS mTSI Direction Y'                         };...
    {'Initial QRS mTSI Direction Z'                         };...
    {'Terminal QRS mTSI Direction X'                        };...
    {'Terminal QRS mTSI Direction Y'                        };...
    {'Terminal QRS mTSI Direction Z'                        };...
    {'Terminal QRS-ST 110-150 mTSI Direction X'             };...
    {'Terminal QRS-ST 110-150 mTSI Direction Y'             };...
    {'Terminal QRS-ST 110-150 mTSI Direction Z'             };...
    {'STpeak mTSI Direction X'                              };...
    {'STpeak mTSI Direction Y'                              };...
    {'STpeak mTSI Direction Z'                              };...
    {'Tpeak-Tend mTSI Direction X'                          };...
    {'Tpeak-Tend mTSI Direction Y'                          };...
    {'Tpeak-Tend mTSI Direction Z'                          };...
    {'QRS mTSI Direction X'                                 };...
    {'QRS mTSI Direction Y'                                 };...
    {'QRS mTSI Direction Z'                                 };...
    {'STT mTSI Direction X'                                 };...
    {'STT mTSI Direction Y'                                 };...
    {'STT mTSI Direction Z'                                 };...
    {'VCG QRS axis X'                                       };...
    {'VCG QRS axis Y'                                       };...
    {'VCG QRS axis Z'                                       };...
    {'VCG QRS axis length'                                  };...
    {'VCG Twave axis X'                                     };...
    {'VCG Twave axis Y'                                     };...
    {'VCG Twave axis Z'                                     };...
    {'VCG Twave axis length'                                };...
    {'temp3'                                                };...
    {'temp4'                                                };...
    {'Pwave first Inflection point'                         };...
    {'VCG Pwave axis X'                                     };...
    {'VCG Pwave axis Y'                                     };...
    {'VCG Pwave axis Z'                                     };...
    {'Pwave Location X'                                     };...
    {'Pwave Location Y'                                     };...
    {'Pwave Location Z'                                     };...
    {'Initial Pwave Location X'                             };...
    {'Initial Pwave Location Y'                             };...
    {'Initial Pwave Location Z'                             };...
    {'TerminalPwave Location X'                             };...
    {'Terminal Pwave Location Y'                            };...
    {'Terminal Pwave Location Z'                            };...
    {'Pwave DirectionX'                                     };...
    {'Pwave Direction Y'                                    };...
    {'Pwave Direction Z'                                    };...
    {'Initial Pwave Direction X'                            };...
    {'Initial Pwave Direction Y'                            };...
    {'Initial Pwave Direction Z'                            };...
    {'TerminalPwave Direction X'                            };...
    {'Terminal Pwave Direction Y'                           };...
    {'Terminal Pwave Direction Z'                           };...
    {'QRS location 0-90 X'                                  };...
    {'QRS location 0-90 Y'                                  };...
    {'QRS location 0-90 Z'                                  };...
    {'ST location 90-170 X'                                 };...
    {'ST location 90-170 Y'                                 };...
    {'ST location 90-170 Z'                                 };...
    {'QRS location 0-30 X'                                  };...
    {'QRS location 0-30 Y'                                  };...
    {'QRS location 0-30 Z'                                  };...
    {'QRS location 30-60 X'                                 };...
    {'QRS location 30-60 Y'                                 };...
    {'QRS location 30-60 Z'                                 };...
    {'QRS location 60-90 X'                                 };...
    {'QRS location 60-90 Y'                                 };...
    {'QRS location 60-90 Z'                                 };...
    {'ST location 90-130 X'                                 };...
    {'ST location 90-130 Y'                                 };...
    {'ST location 90-130 Z'                                 };...
    {'ST location 130-170 X'                                };...
    {'ST location 130-170 Y'                                };...
    {'ST direction 130-170 Z'                               };...
    {'QRS direction 0-90 X'                                 };...
    {'QRS direction 0-90 Y'                                 };...
    {'QRS direction 0-90 Z'                                 };...
    {'ST direction 90-170 X'                                };...
    {'ST direction 90-170 Y'                                };...
    {'ST direction 90-170 Z'                                };...
    {'QRS direction 0-30 X'                                 };...
    {'QRS direction 0-30 Y'                                 };...
    {'QRS direction 0-30 Z'                                 };...
    {'QRS direction 30-60 X'                                };...
    {'QRS direction 30-60 Y'                                };...
    {'QRS direction 30-60 Z'                                };...
    {'QRS direction 60-90 X'                                };...
    {'QRS direction 60-90 Y'                                };...
    {'QRS direction 60-90 Z'                                };...
    {'ST direction 90-130 X'                                };...
    {'ST direction 90-130 Y'                                };...
    {'ST direction 90-130 Z'                                };...
    {'ST direction 130-170 X'                               };...
    {'ST direction 130-170 Y'                               };...
    {'ST direction 130-170 Z'                               };...
    {'CineECG activation in normal range'                   };...
    {'CineECG earlyST in normal range'                      };...
    {'CineECG STT in normal range'                          };...
    {'CineECG 0-110 in normal range'                        };...
    {'CineECG 110-200 in normal range'                      };...
    {'CineECG 200 tpeak in normal range'                    };...
    {'CineECG tptend in normal range'                       };...
    {'ECG activation in normal range'                       };...
    {'ECG earlyST in normal range'                          };...
    {'ECG STT in normal range'                              };...
    {'ECG 0-110 in normal range'                            };...
    {'ECG 110-200 in normal range'                          };...
    {'ECG 200 tpeak in normal range'                        };...
    {'ECG tptend in normal range'                           };...
    {'HP classification'                                    };...
    {'discordant QRS Twave'                                 };...
    {'CineECG iso QRST angle'                               };...
    {'CineECG 0-89 in normal  range'                        };...
    {'CineECG 90-169 in normal   range'                     };...
    {'CineECG 0-29 in normal   range'                       };...
    {'CineECG 30-59 in normal    range'                     };...
    {'CineECG 60-89 in normal   range'                      };...
    {'CineECG 90-129 in normal   range'                     };...
    {'CineECG 130-169 in normal   range'                    };...
    {'CineECG 170 - Tpeak in normal   range'                };...
    {'ECG 0-89 in normal range'                             };...
    {'ECG 90-169 in normal range'                           };...
    {'ECG 0-29 in normal range'                             };...
    {'ECG 30-59 in normal range'                            };...
    {'ECG 60-89 in normal range'                            };...
    {'ECG 90-129 in normal range'                           };...
    {'ECG 130 - 169 in normal range'                        };...
    {'ECG 170 - Tpeak in normal range'                      };...
    {'STT segment'                                          };...
    {'LvSTT segment'                                        };...
    {'ischemia Estimate'                                    };...
    {'median Twave Slope Dominant TMP'                      };...
    {'median Twave SlopeRms'                                };...
    ];