%DETECT is a window setting tool.
%note that detect.m is a script so all variables are local. After closing the 
%countervariable (detc) and detmat are not cleared from the 
 
% File: detect.m
% Date: 12-febr-1998
% By: Henk Nieuwenhuizen
 
CurFig=gcf;

%get ranges for plotting the number of savings
 YRANGE1=get(gca,'Ylim');
 YRANGE=abs(YRANGE1(1) - YRANGE1(2));
 XRANGE=get(gca,'Xlim');
 XRANGE=abs(XRANGE(1) - XRANGE(2));

CurAx=gca;

%UIFig=figure

%counters
 detc=0;
 LineNum=0;  
%callback for the mouse-motion function
Bmotfcn = [ 'CurAx=get(gcf,''CurrentAxes'');'...
            'pt = get(CurAx,''CurrentPoint'');'...
            'xbox=findobj(''Tag'',''Tex_x'');'...
            'set(xbox,''String'',num2str(pt(1,1)));'...
            'ybox=findobj(''Tag'',''Tex_y'');'...
            'set(ybox,''String'',num2str(pt(1,2)));'];

%callback for window-button-down function
pd=['CurAx=get(gcf,''CurrentAxes'');'...
    'pt = get(CurAx,''CurrentPoint'');'... 
    'set(findobj(''Tag'',''Edit_x''),''String'',num2str(pt(1,1),5)),',...
    'set(findobj(''Tag'',''Edit_y''),''String'',num2str(pt(1,2),5)),',...
    'hold on,','YRANGE1=get(gca,''YLim'');,',...
    'LineNum=LineNum+1;,',...
    'getpl(LineNum)=plot([pt(1,1),pt(1,1)],YRANGE1,''r'');,',...
    'hold off,',...
    'set(gcbf,''Pointer'',''default''),',...
    'set(gcbf,''WindowButtonDownFcn'',''default'')'];

%callback for save button
sav=['set(gcbo,''Enable'',''off''),',...
  'detc=detc+1;,',...
  'detmat(detc,1)=str2num(get(findobj(''Tag'',''Edit_x''),''String''));,',...
  'detmat(detc,2)=str2num(get(findobj(''Tag'',''Edit_y''),''String'')),',... 
  'text(detmat(detc,1)+0.002*XRANGE,detmat(detc,2)+0.02*YRANGE,num2str(detc))'];

%callback for detect button
det=['set(CurFig,''Pointer'',''fullcross''),',...
     'set(CurFig,''WindowButtonMotionFcn'',Bmotfcn),',...
     'set(CurFig,''WindowButtonDownFcn'', pd),',...
     'set(Pbsave,''Enable'',''on'')'];

%calback for close button to clear the variables and delete the objecthandles
clvar=['delete(Texx,Texy,Pbsave,Editx,Edity,Pbdet,Pbclose,Pbaxsel,Radzoom,Pbdel);,',...
     'clear Bmotfcn Pbdet XRANGE sav ybox Editx Pbsave YRANGE pd Edity Pbdel;,',...
     'clear Pbaxsel Radzoom czoom Texx det getpl xbox Pbclose Texy detc pt clvar;,',...
     'clear CurAx CurFig LineNum YRANGE1;,',...
     'set(gcbf,''Pointer'',''default'')'];           

%callback for the zoom button
 czoom=['zoom,','if get(gcbo,''Value'')==0,','zoom out,','zoom off,','end'];

%The User interfaces     

Texx = uicontrol(CurFig,'Style','Text','Position',[1 1 40 15],...
       'String','','Backgroundcolor',[0 0  0],'ForegroundColor',[1 1 1],...
       'Tag','Tex_x');

Texy = uicontrol(CurFig,'Style','Text','Position',[45 1 40 15],...
       'String','','Backgroundcolor',[0 0  0],'ForegroundColor',[1 1 1],...
       'Tag','Tex_y');

Pbsave= uicontrol(CurFig,'Style','push','Position',[100 1 40 20],...
          'String','Save','Tag','sav_pb','Callback',sav);

Editx = uicontrol(CurFig,'Style','Edit','Position',[140 1 52.5 20],...
        'BackgroundColor',[1 1 1],'String', '-','Tag','Edit_x');

Edity = uicontrol(CurFig,'Style','Edit','Position',[192.5 1 52.5 20],...
        'BackgroundColor',[1 1 1],'String', '-','Tag','Edit_y');

Pbdet = uicontrol(CurFig,'Style','push','Position',[245 1 45 20],...
        'String','Detect',...
        'Callback',det);

Radzoom= uicontrol(CurFig,'Style','radio','Position',[295 1 60 20],...
         'String','Zoom','Callback',czoom);

Pbdel= uicontrol(CurFig,'Style','push','Position',[360 1 50 20],...
         'String','Delete','Callback','delete(getpl(LineNum));LineNum=LineNum-1;');

Pbaxsel= uicontrol(CurFig,'Style','push','Position',[415 1 80 20],...
         'String','Show Values','Callback','valuedet');

Pbclose= uicontrol(CurFig,'Style','push','Position',[500 1 40 20],...
         'String','Close','Callback', clvar);


%Mouse functions

set(CurFig,'WindowButtonMotionFcn',Bmotfcn);     
set(findobj('Tag','sav_pb'),'Enable','off')
