% pdmltr_anal.m

% general expression for computing the potentials at a single point obs generated by
% either of three monolayers whose strengths are linearly distributed
% over a single triangle with unit strenth at one
% vertex and zero at the respective other two.
% A. van Oosterom; 2011-02-15;
% in: Biomedical Engineering Handbook, 4th edition. Volume: Biomedical Engineering Fundamentals,
% section: Bioelectric Phenomena. Editor R.C. Bar; IN PRESS
% also: Med Biol Eng Comput 2012; 50(1),1-9.
% VER(:,1:3):  the 3 vertices of the triangle
% The leading part treats the singular case in which obs is at one of the
% vertices. This result relates to applications
% in the Boundary Element Method
% The general situation, i.e  including the singular case
% Educatonal variant of dml

% calling: solida; norm3d; icyc;

function phi=pdmltr_anal(VER,obs)

E=VER([2 3 1],:)-VER([1 2 3],:);
% edges of the triangle; note: E(1,:) + E(2,:) + E(3,:)=[0 0 0]

e=norm3d(E);
% lengths of edges

if e(1)==0 | e(2)==0 | e(3)==0,
    'collapsed triangle'
    phi=0;
    return
end

phi=zeros(3,1);
j=find(norm3d(VER-ones(3,1)*obs)<=eps);

if isempty(j)==0
    %'obs at vertex j'
    
    k=j; l=icyc(k+1,3); m=icyc(k+2,3);
    
    a=e(k); c=e(l); b=e(m);
    
    % for P, the projection of singular source node k on the edge opposite;
    % p, the (signed) length of the vector from nodes l to P
    
    p=-E(k,:)*E(l,:)'/c;
    h=sqrt(a^2-p^2);
    gam=log( ((b+c)^2-a^2)/(b^2-(a-c)^2)); % proportional to: potential at obs generated by a uniform line density at edge c
    % phi(k;uniform)=h*gam; integral over unit surface density along narrow
    % strips (width delta(h))parallel to edge c, each contributing the same to phi, owing to the
    % scaling invariance of the potential generated by line sources.
    phi(k)=h/2*gam; % phi at obs; unit density at vertex j=k
    phi(l)=h/2*((a-b)/c+(b^2+c^2-a^2)/(2*c^2)*gam);
    phi(m)=phi(k)-phi(l);
    phi=phi';
    
else
    
    R=VER-ones(3,1)*obs;
    ITRI=[1 2 3];
    
    k=[1 2 3];
    l=[2 3 1];
    m=[3 1 2];
    
    [omega,index]=solida(R,ITRI,[0 0 0]);
    
    r=norm3d(R); % lengths of vectors specifying triangle vertices
    
    En=E./(e*ones(1,3));
    n=cross(E(1,:),E(2,:));
    normn=norm(n);         % twice the area of the source triangle
    u_n=n/normn;           % unit normal of the source triangle
    
    block=0; h_tetra=0;
    if index==0,
        block=det(R);
        h_tetra=block/normn;   % signed distance between [obs] and the
        % plane of the source triangle
        % height of the tetrahedron
    end
    
    ww=zeros(3,1);
    
    % potentials resulting from line source strengths along the separate edges
    
    ww(k)  = det3d(R(k,:),R(l,:),ones(3,1)*u_n)./e(k); % dimension m^2
    %  ww: the signed distance between the projection of obs
    %      on the plane of the source triangle and the line carrying edge(k)
    
    gam=log ((r(l).*e(k)  + sum(R(l,:).*E(k,:),2)+ ones(3,1)*eps )./ ...
        (abs(r(k).*e(k)  + sum(R(k,:).*E(k,:),2))+ ones(3,1)*eps ) );
    % NB: independent of scaling
    % including eps and using the absolute value of the numerator treats (near)zero/(near(zero) singularities
    if index==0, % obs not in plane triangle
        uniform= h_tetra * omega +  ww'*gam; % dimension [m]  uniform (monolayer!!
    else,
        uniform= ww'*gam;
    end
    
    Q_sq= r(l).^2-r(k).^2-e(k).^2;
    D= Q_sq.^2   -4*r(k).^2.*e(k).^2;
    
    % I = contour integral along the edges of the function r(lambda)
    I= r(l).*e(k)/2  +  Q_sq.*(r(l)-r(k))./(4*e(k)) -  D./(8*e(k).^2).*gam;
    
    % cross products ; normals to the tetrahedron faces other than the source
    % triangle
    Z=cross(R(l,:),R(m,:));
    
    phi=(uniform*Z*u_n' -  E(l,:)*En(k,:)'*I)/normn;
    if size(phi,1)>1,phi=phi'; end
end



% some additional identification of the above expressions
%  a=e(k); c=e(l); b=e(m);
%
% % for P, the projection of singular source node k on the opposite edge;
% % p, the (signed) length of the vector from node l to P
%
%    p=-E(k,:)*E(l,:)'/e(l);
%    h=sqrt(e(k)^2-p^2);
%    % all line sources parallel to edge c
%    gam=log( ((e(m)+e(l))^2-e(k)^2)/(e(m)^2-(e(k)-e(l))^2)); %(independent of scaling)
%
%    phi(k)=h/2*gam;  % uniform line source density along all lines parallel to edge c; %  phi(k)=0.5 phi(k;uniform)
%    % strength linearly increasing from edge c to opposite (source).
%
%    phi(l)=h/2*((e(k)-e(m))/e(l)+(e(m)^2+e(l)^2-e(k)^2)/(2*e(l)^2)*gam); % expression following h/2 independent of scaling
%    % strength increasing linearly toward edge a.
%
%    phi(m)=phi(k)-phi(l);   % since: phi(k,uniform)=2*phi(k)=phi(k)+phi(l)+phi(m)

%    Z(1,:)=cross(R(2,:),R(3,:));    % normal to face not including vertex 1; includes edge 2
%    Z(2,:)=cross(R(3,:),R(1,:));    % normal to face not including vertex 2; includes edge 3
%    Z(3,:)=cross(R(1,:),R(2,:));    % normal to face not including vertex 3; includes edge 1



