% cgmadip.m
% function G=cgmadip(VER,DIPS)
% function of forward.m computing the infinite medium potential
% generated by dipoles DIPS(:,1:3)  position
%                      DIPS(:,4:6) strength
% asuming unit conductivity      

function G=cgmadip(OBS,DIPS)
[nobs idum]=size(OBS);
[nsrc idum]=size(DIPS);       
G=zeros(nobs,nsrc);
for k=1:nsrc,
   R=OBS-ones(nobs,1)*DIPS(k,1:3);
   r=norm3d(R);
   ss=find(r>eps);  
   if isempty(ss)==0, G(ss,k)=dots(R(ss,:),DIPS(k,4:6))./r(ss).^3;end
end

G=G/(4*pi);
       	  