% pdmltr.m
% function w=pdmltr(VER,obs,lmax,small)
% contributions to field point obs generated by a DISTRIBUTED
% monolayer at vertexes VERS of a SINGLE triangle 
% small: if the relative change between subsequent iterations
% is less than small the iterative process is terminated 
% in fact: it computes the integrals of 1/r multiplied by the linear shape
% functions at each of the vertices

% A. van Oosterom; 20100301

% NB: if obs lies at a vertex the triangle a special analytical
% treatment of the singularity is effected.
% this part of the algorithm HAS NOT YET BEEN PUBLISHED

% In all other cases:
% a direct numerical summation is invoked, using iteratve 
% refinement of the triangle
% lmax: maximal number of subdevisions of all triangles

function w=pdmltr(VER,obs,lmax,small)

 R=VER-ones(3,1)*obs; 
 E=VER([2 3 1],:)-VER([1 2 3],:);  
 % edges of the triangle; note: E(1,:) + E(2,:) + E(3,:)=[0 0 0]
 e=norm3d(E);
 % lengths of edges
 
 
 if e(1)==0 | e(2)==0 | e(3)==0,
    'collapsed triangle'
    return 
 end
 w=ones(1,3);

j=find(norm3d(VER-ones(3,1)*obs)<=eps);

if isempty(j)==0
    %'obs at vertex j' 
  
    k=j; l=icyc(k+1,3); m=icyc(k+2,3);
    %a=e(k); c=e(l); b=e(m);  
      
% for P, the projection of singular source node k on the opposite edge; 
% p, the (signed) length of the vector from node l to P
  
   p=-E(k,:)*E(l,:)'/e(l);
   h=sqrt(e(k)^2-p^2);
   % all line sources parallel to edge c
   gam=log( ((e(m)+e(l))^2-e(k)^2)/(e(m)^2-(e(k)-e(l))^2)); %(independent of scaling)
   
   w(k)=h/2*gam;  % uniform line source density along all lines parallel to edge c; %  phi(k)=0.5 phi(k;uniform)
   % strength linearly increasing from edge c to opposite (source).
   
   w(l)=h/2*((e(k)-e(m))/e(l)+(e(m)^2+e(l)^2-e(k)^2)/(2*e(l)^2)*gam); % expression following h/2 independent of scaling
   % strength increasing linearly toward edge a. 
   
   w(m)=w(k)-w(l);   % since: phi(k,uniform)=2*phi(k)=phi(k)+phi(l)phi(m);
   
 
else,  
     
% treatment of observation points that do not coincide wth a vertex
  area=norm3d(cross(E(1,:),E(2,:)))/2;
  VER=VER-ones(3,1)*obs;
  rn=(norm3d(VER))';

  % vertex contributions:
  for i=1:3,
    sumv(i)=0;
    if rn(i) > 2*eps,sumv(i)=1/(3*rn(i)); end
  end
  w=sumv; wo=w; woa=w;
  l=1;
  % initialize contributions of rim nodes and internal nodes
  sumi=zeros(1,3); sumr=zeros(1,3);
  % fr(i) expresses bilinear weight of node(i)=1, while taking the other two 
  % nodes value zero
  fr=zeros(1,3);
  while l<=lmax/2,
     l=l*2;
     for i=1:l,
       jb=i-fix(i/2)*2+1;
       fr(2)=(i-1)/l;
       for j=jb:jb:l+2-i,
          fr(3)=(j-1)/l; fr(1)=1-fr(2)-fr(3);
	  % r at node treated:
	  r=norm(fr*VER);
	  if r > 2*eps,
	     if i==1|j==1|i+j==l+2,
	        sumr=sumr+fr/r;
	     else, 
	        sumi=sumi+2*fr/r;
	     end
	  end
	end
     end
     w=(sumv+sumr+sumi)/l^2;
     % test for pseudo convergence using Richardson extrapolation
     % see paper with Meijs (1989) on Richardson extrapolation
     wa=w+(w-wo)/3.;
     if norm(wa-woa)/(norm(woa)+eps) < small, break; end
     wo=w;
     woa=wa;
   end
   w=wa*area;
end     
     	     	 