function TABLE = readCineECGFromImapLog2Table(fn)
% [~,TXT,~] =
% xlsread('D:\users\peter\Peacs\Code\Cync\PollyMapper\logPollyMapperheader.xlsx');TXT=TXT(1,2:end)'
HEAD =[{'date'                                                                                                                         };...
    {'patient ID'                                                                                                                   };...
    {'model'                                                                                                                        };...
    {'Svolume'                                                                                                                      };...
    {'Lvolume'                                                                                                                      };...
    {'Rvolume'                                                                                                                      };...
    {'ECG case'                                                                                                                     };...
    {'ECG file'                                                                                                                     };...
    {'type'};...
    {'QRS  duration'                                                                                                                };...
    {'Ohmega point'                                                                                                                      };...
    {'QT'                                                                                                               };...
    {'Peak T wave'                                                                                                                  };...
    {'relative ST  '                                                                                                                };...
    {'mode'                                                                                                                         };...
    {'RV  focus'                                                                                                                  };...
    {'LV focus'                                                                                                                   };...
    {'initial angle'                                                                                                                };...
    {'LV latest'                                                                                                                   };...
    {'RV latest'                                                                                                                  };...
    {'mean TSI distance'                                                                                                          };...
    {'distance focus to latest'                                                                                                  };...
    {'qrs area'                                                                                                                     };...
    {'3D qrs area'                                                                                                                  };...
    {'KORS qrs area'                                                                                                                };...
    {'KORS 3D qrs area'                                                                                                             };...
    {'TCR QRS'                                                                                                                      };...
    {'minimum TCR QRS'                                                                                                              };...
    {'TCR STT'                                                                                                                      };...
    {'TCR Beat'                                                                                                                     };...
    {'mean QRS VCG axis X'                                                                                                          };...
    {'mean QRS VCG axis Y'                                                                                                          };...
    {'mean QRS VCG axis Z'                                                                                                          };...
    {'mean QRS VCG axis norm'                                                                                                       };...
    {'QRS mTSI Location  Septum'                                                                                                    };...
    {'QRS mTSI Location  LV'                                                                                                        };...
    {'QRS mTSI Location RV'                                                                                                         };...
    {'STT mTSI Location Septum'                                                                                                     };...
    {'STT mTSI Location  LV'                                                                                                        };...
    {'STT mTSI Localization  RV'                                                                                                    };...
    {'Terminal QRS mTSI Location Septum'                                                                                            };...
    {'Terminal QRS mTSI Location LV'                                                                                                };...
    {'Terminal QRS mTSI Location RV'                                                                                                };...
    {'Terminal QRS-ST mTSI 110-150 Location Septum'                                                                                 };...
    {'Terminal QRS -ST 110-150 mTSI  Location  LV'                                                                                  };...
    {'Terminal QRS-ST 110-150 mTSI  Location  RV'                                                                                   };...
    {'STpeak mTSI Location Septum'                                                                                                  };...
    {'STpeak mTSI Location LV'                                                                                                      };...
    {'STpeak mTSI Location RV'                                                                                                      };...
    {'Tpeak-Tend mTSI Location Septum'                                                                                              };...
    {'Tpeak-Tend mTSI Location LV'                                                                                                  };...
    {'Tpeak-Tend mTSI Location RV'                                                                                                  };...
    {'Initial QRS mTSI Direction X'                                                                                                 };...
    {'Initial QRS mTSI Dircetion Y'                                                                                                 };...
    {'Initial QRS mTSI Dircetion Z'                                                                                                 };...
    {'Terminal QRS mTSI Direction X'                                                                                                };...
    {'Terminal QRS mTSI Direction Y'                                                                                                };...
    {'Terminal QRS mTSI Direction Z'                                                                                                };...
    {'Terminal QRS-ST 110-150 mTSI  Direction X'                                                                                    };...
    {'Terminal QRS-ST 110-150 mTSI  Direction Y'                                                                                    };...
    {'Terminal QRS-ST 110-150 mTSI  Direction Z'                                                                                    };...
    {'STpeak mTSI Direction X'                                                                                                      };...
    {'STpeak mTSI Direction Y'                                                                                                      };...
    {'STpeak mTSI Direction Z'                                                                                                      };...
    {'Tpeak-Tend mTSI Direction X'                                                                                                  };...
    {'Tpeak-Tend mTSI Direction Y'                                                                                                  };...
    {'Tpeak-Tend mTSI Direction Z'                                                                                                  };...
    {'initial Vector in myocard'                                                                                                    };...
    {'template nr'                                                                                                                  };...
    {'relative direction onset QRS x'                                                                                               };...
    {'relative direction onset QRS y'                                                                                               };...
    {'relativedirection onset QRS z'                                                                                                };...
    {'relative direction QRS x'                                                                                                     };...
    {'relative direction QRS y'                                                                                                     };...
    {'relative direction QRS z'                                                                                                     };...
    {'relative direction terminal QRS-ST150 X'                                                                                      };...
    {'relative direction terminal QRS-ST150 Y'                                                                                      };...
    {'relative direction terminal QRS-ST150 Z'                                                                                      };...
    {'relative initial T-wave X'                                                                                                    };...
    {'relative initial T-wave Y'                                                                                                    };...
    {'relative initial T-wave Z'                                                                                                    };...
    {'relative Terminal T-wave X'                                                                                                   };...
    {'relative Terminal T-wave Y'                                                                                                   };...
    {'relative Terminal T-wave Z'                                                                                                   };...
    ]';

if exist(fn)
    status = copyfile(fn, 'c:/temp/tmp.csv');
    TABLE  = readtable('c:/temp/tmp.csv','Delimiter',',');
    delete('c:/temp/tmp.csv')
    if size(TABLE,2) > size(HEAD,2)
        TABLE(:,size(HEAD,2)+1:end) =[];
    end
    TABLE.Properties.VariableNames = HEAD';
    remove = 1:length(HEAD);
    use = [2 8 9 10 12:length(HEAD)];
    remove(use)=[];
    TABLE = removevars(TABLE, HEAD(remove));
else
    error(['file: ' fn ' does not exist']);
end
    





