function TABLE = readPollyLog2Table(fn)

HEADV5000 = header5000();
HEADV5500 = header5500();
HEADV6948 = header6948();

if exist(fn,'file')
    TABLE  = readtable(fn,'Delimiter',',');
    if size(TABLE,2) == size(HEADV5000,2)
        TABLE.Properties.VariableNames = HEADV5000;
    elseif size(TABLE,2) == size(HEADV5500,2)
        TABLE.Properties.VariableNames = HEADV5500;
    elseif size(TABLE,2) == size(HEADV6948,2)
        TABLE.Properties.VariableNames = HEADV6948;
    else
        error('no matching header definition')
    end
    % if size(TABLE,2)== 56
    %     HEAD = HEAD([1:8 10:end]);
    % elseif size(TABLE,2)== 57
    %     HEAD = [HEAD EXTRANEW'];
    %     A= zeros(size(TABLE,1),5);
    %     for i=1:size(TABLE,1)
    %         str = strsplit(cell2mat(TABLE{i,end}),' ');
    %         for j=1:length(str)
    %             A(i,j) = str2num(str{j});
    %         end
    %     end
    %     TABLE = TABLE(:,1:end-1);
    %     for j=1:size(A,2)
    %         eval(['A' num2str(j) '= A(:,j);']);
    %         eval(['TABLE = [TABLE table(A' num2str(j) ')];']);
    %     end
    % elseif size(TABLE,2) > size(HEAD,1)
    %     HEAD = [HEAD EXTRANEW'];
    % end
    % TABLE.Properties.VariableNames = HEAD';
    % remove = 1:length(HEAD);
    % use = [2:6 8:length(HEAD)];
    % remove(use)=[];
    % TABLE = removevars(TABLE, HEAD(remove));
else
    error(['file: ' fn ' does not exist']);
end




%%
function HEADV6948 = header6948()
TABLE  = readtable('logPollyMapperheader version 6948.xlsx');
HEADV6948 = TABLE.Properties.VariableNames(2:end);

%%
function HEAD = header5000()

HEAD =[{'date'      };...
    {'patient ID'   };...
    {'model'        };...
    {'Svolume'      };...
    {'Lvolume'      };...
    {'Rvolume'      };...
    {'ECG case'     };...
    {'ECG file'     };...%
    {'RR int'       };...
    {'type'};...
    {'QRS  duration'};...
    {'Ohmega point' };...
    {'QT'           };...
    {'QTc Bazett'   };...
    {'Peak T wave'  };...
    {'relative ST  '};...
    {'KORS qrs area'};...
    {'LAT max'      };...
    {'LAT std'      };...
    {'mean LV LAT'  };...
    {'mean RV LAT'  };...
    {'mean Septal LAT'};...
    {'std LV LAT'   };...
    {'std RV LAT'   };...
    {'std Septal LAT'};...
    {'initial LV LAT'};...
    {'initial RV LAT'};...
    {'initial Septal LAT'   };...
    {'last LV LAT'  };...
    {'last RV LAT'  };...
    {'last Septal LAT'};...
    {'septal Papillary LAT' };...
    {'lateral papillary LAT'};...
    {'mLVDelayVector X (heart system)'};...
    {'LVDelay Vector Y (heart system)'};...
    {'LVDelay Vector Z (heart system)'};...
    {'Epicardial VEU'};...
    {'Std LAT Epicardium'   };...
    {'LV mass at 0.33'};...
    {'RV mass at 0.33'};...
    {'SEPTAL mass at 0.33'  };...
    {'LV mass at 0.5'};...
    {'RV mass at 0.5'};...
    {'SEPTAL mass at 0.5'   };...
    {'LV mass at 0.66'};...
    {'RV mass at 0.66'};...
    {'SEPTAL mass at 0.66'  };...
    {'LV mass mean' };...
    {'RV mass mean' };...
    {'SEPTAL mass mean'};...
    {'VEU LV septum'};...
    {'VEU RV septum'};...
    {'VEU LV RV'    };...
    {'correlation'  };...
    {'septal blush velocity'};...
    {'nr LV foci'   };...
    {'Initial Dep Velocity' };...
    ]';

%%
function HEAD = header5500()

HEAD =[{'date'      };...
    {'patient ID'   };...
    {'model'        };...
    {'Svolume'      };...
    {'Lvolume'      };...
    {'Rvolume'      };...
    {'ECG case'     };...
    {'ECG file'     };...%
    {'RR int'       };...
    {'type'};...
    {'QRS  duration'};...
    {'Ohmega point' };...
    {'QT'           };...
    {'QTc Bazett'   };...
    {'Peak T wave'  };...
    {'relative ST  '};...
    {'KORS qrs area'};...
    {'LAT max'      };...
    {'LAT std'      };...
    {'mean LV LAT'  };...
    {'mean RV LAT'  };...
    {'mean Septal LAT'};...
    {'std LV LAT'   };...
    {'std RV LAT'   };...
    {'std Septal LAT'};...
    {'initial LV LAT'};...
    {'initial RV LAT'};...
    {'initial Septal LAT'   };...
    {'last LV LAT'  };...
    {'last RV LAT'  };...
    {'last Septal LAT'};...
    {'septal Papillary LAT' };...
    {'lateral papillary LAT'};...
    {'mLVDelayVector X (heart system)'};...
    {'LVDelay Vector Y (heart system)'};...
    {'LVDelay Vector Z (heart system)'};...
    {'Epicardial VEU'};...
    {'Std LAT Epicardium'   };...
    {'LV mass at 0.33'};...
    {'RV mass at 0.33'};...
    {'SEPTAL mass at 0.33'  };...
    {'LV mass at 0.5'};...
    {'RV mass at 0.5'};...
    {'SEPTAL mass at 0.5'   };...
    {'LV mass at 0.66'};...
    {'RV mass at 0.66'};...
    {'SEPTAL mass at 0.66'  };...
    {'LV mass mean' };...
    {'RV mass mean' };...
    {'SEPTAL mass mean'};...
    {'VEU LV septum'};...
    {'VEU RV septum'};...
    {'VEU LV RV'    };...
    {'correlation'  };...
    {'septal blush velocity'};...
    {'nr LV foci'   };...
    {'Initial Dep Velocity' };...
    {'HP LV septal'};...
    {'HP LV anterior'    };...
    {'HP LV posterior'  };...
    {'HP RV septal'};...
    {'HP RV free wall'   };...
    {'Latest LV septal'};...
    {'Latest LV anterior'    };...
    {'Latest LV posterior'  };...
    {'Latest RV septal'};...
    {'Latest RV free wall'   };...
    {'Mass50% LV septal'};...
    {'Mass50% LV anterior'    };...
    {'Mass50% LV posterior'  };...
    {'Mass50% RV septal'};...
    {'Mass50% RV free wall'   };...

    ]';

